### ISSUE TITLE
Inconsistency in the Grammar of 'Predefined Steps' related to 'co-ordinates'

### ISSUE THREAD

**Issue by dineshb-qa** [selenium-cucumber/selenium-cucumber-ruby#1]
**Steps to Reproduce :**
- Go to [Swipe steps](https://github.com/selenium-cucumber/selenium-cucumber-ruby/blob/master/doc/canned_steps.md#swipe-steps)
  - See the **To perform swipe using co-ordinates with direction use following steps :** => Then I swipe from **co-ordinates "(._?)","(._?)" to **co-ordinates** "(._?)","(._?)"
  - See the To perform swipe using **co-ordinates**  => Then I swipe from **co-ordinates** "(._?)","(._?)" to co-ordinates "(._?)","(._?)"
- Now go to [long tap steps](https://github.com/selenium-cucumber/selenium-cucumber-ruby/blob/master/doc/canned_steps.md#long-tap-steps)
  - See the **To perform long tap with default duration of 2 seconds using co-ordinates use following step :**  => Then I long tap on **co\ -ordinate** "(._?)","(._?)
  - See the **To perform long tap with customized duration of seconds using co-ordinates use following step :** => Then I long tap on **co\ -ordinate** "(._?)","(._?)" for "(.*?)" sec

**Expected Result**
1. The grammar in predefined steps should be consistent.

**Actual Result**
1. The grammar in predefined steps is not consistent. Some steps use **co\ -ordinate** and some use **co-ordinates**

**Comment by sameer49** [comment]
will correct the grammar

thanks
sameer

**Comment by sameer49** [comment]
@dineshb-qa fiexd grammar
changes will be reflected in next version of gem
