### ISSUE TITLE
Need Help : Jenkins Parameters help

### ISSUE THREAD

**Issue by maddysama** [selenium-cucumber/selenium-cucumber-ruby#11]
I would like to understand if we can acheive my requirement using this plugin:
 I have with several columns in a text file. If I select Column1, then I would like to return all other column values in an array OR concatinated string in a specified format and return the string.
 Example:
 ParamProperties.txt:
 Name Address1 City State Zip
 John 1KaisyRd Newton MA 02030
 Kelly 3NelloreRd Weston MA 02032
 Now, I will select Name (John or Kelly), then it should return the parameter string as: 1KaisyRd-Newton-MA-02030.
 I would like to understand if we can acheive my requirement using this plugin:

I have with several columns in a text file. If I select Column1, then I would like to return all other column values in an array OR concatinated string in a specified format and return the string.

Example:

ParamProperties.txt:

NameAddress1CityStateZip

John1KaisyRdNewtonMA02030

Kelly3NelloreRdWestonMA02032

Now, I will select Name (John or Kelly), then it should return the parameter string as: 1KaisyRd-Newton-MA-02030.

**Comment by sameer49** [comment]
This would require to write your own step with your code to achieve what you want.

Thanks,
Sameer
