### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by kkchaurasia** [selenium-cucumber/selenium-cucumber-ruby#12]
Good Day ,
Can anyone please help me how to test transaction on banking application page please.
Thanks

**Comment by sameer49** [comment]
Its domain specific question, it would be your own thinking and logic.

Thanks
Sameer

**Comment by kkchaurasia** [comment]
Yes Sameer thats true.  

But i am looking do we have any commands in Ruby to check the transaction or the row in Ruby .

How we can get the row count using ruby. If you can help please.

**Comment by sameer49** [comment]
You mean using selenium?

**Comment by kkchaurasia** [comment]
Yes

**Comment by sameer49** [comment]
Then you can find that row element and take text out of it
