### ISSUE TITLE
Anyone still maintaining this?

### ISSUE THREAD

**Issue by Carlbc18** [selenium-cucumber/selenium-cucumber-ruby#13]
There are many things that this gem doesn't work with now (cucumber 2.2, selenium 2.53, and ruby 2.3.0, incorporate RSpec Matchers). I'd like to make a PR which overhauls the gem to be up-to-date with current standards, including, but not limited to the above gem mentions, but only if the PR's will be reviewed and merged by the project owner. @sameer49, please let me know if you're willing to review and approve a PR which should improve the flexibility and functionality of the gem.  

Thanks,
Brian

**Comment by sameer49** [comment]
Yes, due to updates into cucumber & selenium this gem has become unstable, we are working on it. I was busy with some other project. 

I aware of PR and checked it locally, once we done with testing will update gem

Thanks,
Sameer

**Comment by Carlbc18** [comment]
@sameer49 i have put up a PR, please review, lets collaborate on it if possible.

**Comment by sameer49** [comment]
ya sure! thanks

**Comment by Carlbc18** [comment]
No problem!

**Comment by Tb0** [comment]
Hello @sameer49, did you have a look on @Carlbc18 PR ?
Would love to see it merged.
Thanks!

**Comment by Carlbc18** [comment]
@Tb0 I need to make a couple changes (i'll do that tonight) from my comments.

@Tb0 changes pushed.

**Comment by Carlbc18** [comment]
@sameer49 have you had a chance to look at things?

**Comment by sandeepnagra** [comment]
I would love to see your updates @Carlbc18 

@sameer49 let me know if you need some help with testing

**Comment by sameer49** [comment]
@Carlbc18 I have merge your PR 

Thanks.
