### ISSUE TITLE
driver.quit in hooks.rb at_exit hook throws error

### ISSUE THREAD

**Issue by sameer49** [selenium-cucumber/selenium-cucumber-ruby#16]
driver.quit in hooks.rb at_exit hook throws following error
`initialize': Connection refused - connect(2) for "127.0.0.1" port 9515 (Errno::ECONNREFUSED)

**Comment by Tb0** [comment]
Did you try to use `close_driver` instead ?
Works for me.

**Comment by Carlbc18** [comment]
It looks like @sameer49 removed the at_exit driver quit call. It works great in FF, but i do see the issue when using chrome.

**Comment by sameer49** [comment]
added begin rescue block, if driver is already closed exception will be handled
