### ISSUE TITLE
How to run jquery code from chrome browser which is started by driver

### ISSUE THREAD

**Issue by taochen2** [selenium-cucumber/selenium-cucumber-ruby#17]
Hello, 

I am trying to prepare TA for web, and try to using chrome browser to run a jquery code:
$driver.execute_script("return $()")
Well error pop up:
$ is not defined (Selenium::WebDriver::Error::JavascriptError)
Is anybody can help to check this?
BTW, if I using Firefox browser, it is OK.

Thanks

**Comment by Carlbc18** [comment]
@taochen2 do you have a stack?

**Comment by taochen2** [comment]
Well, it works now and I don't know why. What I did is change chrome browser to anther version. Current version number is: 52.0.2743.116.
Any way, thanks for your response.

**Comment by Carlbc18** [comment]
could be related. browsers are problematic.
