### ISSUE TITLE
Running any feature opens blank firefox

### ISSUE THREAD

**Issue by gochujang** [selenium-cucumber/selenium-cucumber-ruby#20]
Hi,

I am new to selenium-cucumber-ruby and just started 2 days ago with very minimal experience in programming. I did everything that was stated here (https://seleniumcucumber.info/) in the tutorials for the setup and creating a new project. However, whenever I try to run **any** feature (even the example in the tutorial), it only opens a blank Firefox.

I have the following gems installed:
![image](https://cloud.githubusercontent.com/assets/21210004/17915877/c204113c-69e0-11e6-8343-6f75ff8b65be.png)

I also attached the chrome webdriver location to the path. 

Thanks for any help.

**Comment by Carlbc18** [comment]
What version of FF are you using. There is a known selenium bug in gem version 2.53+ with Firefox 47+. You should downgrade.

https://github.com/SeleniumHQ/selenium/issues/2257
https://github.com/SeleniumHQ/selenium/issues/2110

**Comment by gochujang** [comment]
I'm using FF v48.0.1.. thanks I'll try downgrading.

**Comment by Carlbc18** [comment]
I just checked FF 46 and it works fine.

**Comment by Carlbc18** [comment]
if you like you can simply switch to chrome by either setting the env variable, or changing the default from 'ff' to 'chrome' in the env.rb
