### ISSUE TITLE
Add Release Notes for latest release 3.1.5

### ISSUE THREAD

**Issue by dineshb-qa** [selenium-cucumber/selenium-cucumber-ruby#23]
The [release notes](https://github.com/selenium-cucumber/selenium-cucumber-ruby/releases) are not updated for latest release 3.1.5

Suggestion :
- Whenever there will be new release then please publish the corresponding details or release notes on your [site](https://seleniumcucumber.info/) as well

**Comment by Carlbc18** [comment]
Thank you for pointing that out.  I don't have control over what is published on the site, but i can update the release notes.

**Comment by sameer49** [comment]
@dineshb-qa Yes Sure!

**Comment by dineshb-qa** [comment]
@sameer49 : You Closed this issue but the [release notes](https://github.com/selenium-cucumber/selenium-cucumber-ruby/releases) are still not updated for latest release 3.1.5
