### ISSUE TITLE
api not works when using capybara

### ISSUE THREAD

**Issue by XinWangRita** [selenium-cucumber/selenium-cucumber-ruby#25]
Given(/^I open BVL web login page$/) do
  #navigate_to($url_login)
  visit 'http://10.202.129.83/#/login/'
end

below not works when using capybara
navigate_to($url_login)
error message:
method `find_element' for nil:NilClass (NoMethodError)

**Comment by Carlbc18** [comment]
You need to make sure to assign the capybara instance of the selenium driver to $driver. The canned steps rely on the global $driver variable.
