### ISSUE TITLE
undefined method 'expect' fails most methods in assertion_methods.rb

### ISSUE THREAD

**Issue by sandeepnagra** [selenium-cucumber/selenium-cucumber-ruby#26]
Hi, most of my assertion tests started failing after upgrading to ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32] that I had to do to use another gem.

I get following error.

undefined method `expect' for #<Object:0x00000007787e48> (NoMethodError)

I added require 'rspec/expectations' to my env.rb file as advised here - http://stackoverflow.com/questions/18071777/using-expect-matcher-in-rspec

but that didn't work either. Could you please look into this and advise?

Meanwhile, if I find a solution, I will post it.

**Comment by sandeepnagra** [comment]
Here's a response I received from rspec guys:

RSpec does not add expect to every object (no more monkey patching!) instead only adding it to a the context in which rspec-core examples run (typically, it blocks, before hooks, etc). The fact that the error you reported is undefined method 'expect' for #<Object:0x00000007b1db48> makes it sound like you are running this inside some anonymous object, not in an rspec example.

If you need to use expect in another context, you can mix-in the methods yourself via a module inclusion in your class:

include RSpec::Matchers

**Comment by sameer49** [comment]
@sandeepnagra are running cucumber tests ? because cucumber define Spec::Matchers and Spec::Expectations modules

refer : http://stackoverflow.com/questions/18071777/using-expect-matcher-in-rspec

**Comment by sandeepnagra** [comment]
@sameer49 solved it, the culprit was another gem which had following code:

require ‘rspec’

RSpec.configure do |config|
config.expect_with :rspec do |c|
c.syntax = :should
end
end

Apologies for the confusion. Closing this issue.
