### ISSUE TITLE
How to verify the credit and debit transaction of banking app

### ISSUE THREAD

**Issue by kkchaurasia** [selenium-cucumber/selenium-cucumber-ruby#27]
How to verify the credit and debit transaction of banking app using Ruby .

**Comment by Carlbc18** [comment]
Could you please provide some function code example. Unfortunately your question is hard to answer without some real context

**Comment by kkchaurasia** [comment]
I am working on a banking app where i need to verify the credit and debit transactions . Credit transaction does not have any prefix sign with the amount and debit transaction has the "-"sign as prefix before amount. So if i want to see only debit transaction then i click on out filter which will list the debit transactions.Hope i was able to explain what i am trying to do.

**Comment by sameer49** [comment]
@kkchaurasia you mean, you apply filter to get only debit transaction and verify that result contains only debit transactions ?

**Comment by kkchaurasia** [comment]
@sameer49  thats correct sameer

**Comment by sameer49** [comment]
@kkchaurasia 
In this case you cannot use pre-defined steps you have to write your own custom step.

Verification is simple you have to look for such elements which will differentiate debit and credit transactions, such as you said "-"sign is prefixed for debit transactions, other things can be colour codes or words like debited, withdrawn, credited, deposited.
