### ISSUE TITLE
Failed to open TCP connection to 127.0.0.1:7055 (Connection refused - connect(2) for "127.0.0.1" port 7055) (Errno::ECONNREFUSED)

### ISSUE THREAD

**Issue by ahmeds6** [selenium-cucumber/selenium-cucumber-ruby#28]
Issue Description:

If I run feature scenario A and scenario B together, Scenario A runs ok, but Scenario B throws following error:

Failed to open TCP connection to 127.0.0.1:7055 (Connection refused - connect(2) for "127.0.0.1" port 7055) (Errno::ECONNREFUSED)

But If I run scneario(s) one by one, it's working as expected.

Any thoughts!

I have close_driver method at at_exit.

here is my gem list:

selenium-client (1.2.18)
selenium-cucumber (3.1.5)
selenium-webdriver (3.3.0, 2.53.4, 2.35.1)
cucumber (2.4.0, 2.1.0, 2.0.0)
cucumber-api (0.4)
cucumber-core (1.5.0, 1.3.0, 1.1.3)
cucumber-wire (0.0.1)
json (2.0.3, 2.0.2, 1.8.6, 1.8.3)
json-schema (2.7.0)
jsonapi (0.1.1.beta6, 0.1.1.beta2)
jsonapi-parser (0.1.1.beta3)
jsonapi-renderer (0.1.1.beta1)
jsonpath (0.5.8)

**Comment by sameer49** [comment]
@ahmeds6 
I guess you have added closing browser step i.e **"Then I close browser"** in scenario.

**Comment by ahmeds6** [comment]
I do not have any "Then I close browser" step in the scenario since I have added close_driver method. Any other guess?

**Comment by sameer49** [comment]
@ahmeds6 
Can you post your scenario and your hooks.rb file content ?
