### ISSUE TITLE
Appium session fails:  Failed to start an Appium session, err was: Error: 'java -version' failed. Error: spawn ENOENT

### ISSUE THREAD

**Issue by Pratas0** [selenium-cucumber/selenium-cucumber-ruby#3]
Hello, 

I'm doing some android tests but Appium session fails and i can't perform any test.
I'm using latest appium version, 1.4, in windows 10.

![appium session fails](https://cloud.githubusercontent.com/assets/15092343/10432730/2598a742-7105-11e5-87c9-8ab8ef763fdf.PNG)
Anyone can help me?
Thanks

**Comment by sameer49** [comment]
Is java installed?
Is JAVA_HOME path set?

**Comment by Pratas0** [comment]
Yes, Java is installed and all environment variables correctly defined.

**Comment by sameer49** [comment]
is adb path are set correctly?
