### ISSUE TITLE
Cucumber with Selenium 3

### ISSUE THREAD

**Issue by analyst-anju** [selenium-cucumber/selenium-cucumber-ruby#31]
I have to use selenium 3.0.0 (or higher version) with Cucumber, but I am getting following exception at all times: 
cucumber.runtime.CucumberException: Failed to instantiate class

I tried different version combinations of Selenium and Cucumber like 3.0.0 with 1.2.4 respectively or 3.0.0 with 1.1.8 and so on.

But not able to get rid of exception, does anyone have idea?

**Comment by Carlbc18** [comment]
You're using version 1.18 or 1.24 of cucumber? Cucumbers minimum version dependency with selenium-cucumber 3.1.5 is 2.3.0 and higher.  Could you post your gemspec here?
