### ISSUE TITLE
undefined method `selected?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by sandeepnagra** [selenium-cucumber/selenium-cucumber-ruby#32]
I get error on executing following step on test site.

step %[I select "Male" option by text from radio button group having id "radio_gender"]

I then searched all files under C:\Ruby22-x64\lib\ruby\gems\2.2.0\gems\selenium-cucumber-3.1.5\lib\selenium-cucumber\methods

and couldn't find 'selected?' method defined anywhere. This is going to impact several canned tests.

**Comment by sameer49** [comment]
thanks @sandeepnagra for notifying. I am looking into issue.

**Comment by sameer49** [comment]
@sandeepnagra 
You have passed "radio_gender" as element id but its name of elements on test page https://selenium-cucumber.github.io/ for radio button. 

You should use following step.
`step %[I select "Male" option by text from radio button group having name "radio_gender"]`

**Comment by sandeepnagra** [comment]
Hi Sameer,

Sorry for the typo there, I used name only and still get the same error. It's not just this canned step, any canned step using the method "selected?" is impacted. I couldn't find it in any of the method files in the gem.

**Comment by sameer49** [comment]
@sandeepnagra  ohh, I can reproduce it ! checking and fixing soon.
thanks.

**Comment by sameer49** [comment]
actually its problem with test page, the text of element radio button is not within any markup, so its not able to find text for the radio button. If you use by value its working

`step %[I select "M" option by value from radio button group having name "radio_gender"]`

the step by text should remove, because its not going to work anyway.

**Comment by sandeepnagra** [comment]
Thanks Sameer!

step %[I select "M" option by value from radio button group having name "radio_gender"]

worked but are you saying that canned step for option by text for radio button will not work for any page or just this test page?

And I am still wondering if the 'selected?' in "expect(radio_button.selected?).to be should_be_selected" an rspec or any other third party library method?

**Comment by sameer49** [comment]
get_text() works if text is within mark-up
e.g. `<div id="name">xyz</div>`
it will not work on `<div id="name"></div> xyz`

group elements have multiple elements with same id/name/class, we get list of elements and filter out the element with given text, in this case no text is returning for radio button so nil element is getting from list and its throwing error  undefined method `selected?' for nil:NilClass (NoMethodError)

**Comment by sandeepnagra** [comment]
Thanks for the explanation Sameer.
