### ISSUE TITLE
Generate random email address

### ISSUE THREAD

**Issue by Jas4you** [selenium-cucumber/selenium-cucumber-ruby#34]
Hi @sameer49 , 

I'm quite new to automation testing using selenium-cucumber-ruby and your repository has been very helpful to make me understand how this work. However, i'm a bit lost in one of my steps. It consists of adding a random email address in an input field on a webpage. 

I'm initially tried to use the "enter_text(by, text, access_value)" but i don't know with what to replace the "by" and "access_value" (as i said, i'm very new to ruby and selenium-cucumber)

My aim is to define a method to generate a random string, in my env.rb file and then use it in my step definitions file to form an email address in the following format "auto#{random_string}@test.qa" , but not sure if it will work.

The method i used is as below(found this when searching online) :

def random_string(length=6)
  chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ0123456789'
  string = ''
  length.times { string << chars[rand(chars.size)] }
  string
end

Can you help please?

Thanks

**Comment by sameer49** [comment]
Hi @Jas4you 

You can call step inside step defination
First write your custom step say "**Enter random email address**" in feature file

and implement this step in some ruby(.rb) file like following

```ruby
def random_string(length=6)
        chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ0123456789'
        string = ''
        length.times { string << chars[rand(chars.size)] }
        string
end

Then(/^enter random email address"$/) do
       random_string = random_string()
       random_email = "auto#{random_string}@test.qa"
       step "I enter '"#{random_email}"' into input field having id 'element_id'"
end
```

According to element locator(id, class, name, xpath) change it.

Random_email variable should passed in quoted form  and its value should concatenated that is why it is first quoted in single quote and then double quote  **' "#{random_email}" '**

refer : https://github.com/cucumber/cucumber/wiki/Calling-Steps-from-Step-Definitions

**Comment by Jas4you** [comment]
Thanks a lot @sameer49 

It works. :)

**Comment by waqaszulfiqar** [comment]
I am trying this but getting an error 

`def random_string(length=6)
  chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ0123456789'
  string = ''
  length.times { string << chars[rand(chars.size)] }
  string
end

Then(/^enter random email address"$/) do
  random_string = random_string()
  random_email = "auto#{random_string}@test.qa"
  step "I enter '"#{random_email}"' into input field having id '#email'"
end`


**Error:**

You can implement step definitions for undefined steps with these snippets:

Then('enter random email address') do
  pending # Write code here that turns the phrase above into concrete actions
end
