### ISSUE TITLE
feature display a message "Failed to find width field", blank page is displayed in firefox

### ISSUE THREAD

**Issue by william0096** [selenium-cucumber/selenium-cucumber-ruby#35]
Hello All!
I'm new with selenium-cucumber, I'm trying to execute this tutorial ( https://www.youtube.com/watch?v=QB0-4aHh4cY&index=4&list=PLZt39FrnLVvFfF9vLVNVWzFAm-zw-hR0j ) but when execute the feature, system displays the following message 
![image](https://user-images.githubusercontent.com/30137999/28151319-89d71d9a-675f-11e7-8c12-1eaf9c65fdb3.png)
At same time, a **blank page in firefox is displayed**.

Please find below the code that I'm using
![image](https://user-images.githubusercontent.com/30137999/28151359-c35eb9b0-675f-11e7-9220-196c323e0bf0.png)

**Comment by sameer49** [comment]
Hi @william0096 

Possibly its firefox issue https://github.com/mozilla/geckodriver/issues/820
can you tell me which version of firefox and selenium are you using?
are you using gecko driver?

**Comment by william0096** [comment]
Hi @sameer49 

I'm using gecko dirver

geckodriver 0.18.0
firefox 54.0.1 (64-bit)
platform OS X

**Comment by sameer49** [comment]
Hi @william0096 

Open evn.rb and comment out "**$driver.manage().window().maximize()**" this line.
it will not maximise browser

try this work around, it should work

**Comment by william0096** [comment]
It does not work, but a per mozilla/geckodriver#820, I installed the beta version of Firefox (55 beta).

Now is working.

**Comment by sameer49** [comment]
okay
