### ISSUE TITLE
CucumberExpressionError for few of the Step def.

### ISSUE THREAD

**Issue by anuj-lakra** [selenium-cucumber/selenium-cucumber-ruby#37]
Hello,

On executing few scenario which has step def with regular expression as  \s*((?:  , I am getting CucumberExpressionError. 

Please suggest.

Issue:

**Scenario:** verify page title
		Then I should see page title as "Test Page for selenium–cucumber"

**Expression /^I should\s*((?:not)?)\s+see page title as "(.*?)"$/ has 2 capture groups (["", "Test Page for selenium–cucumber"]), but there were 1 parameter types ([".*?"]) (Cucumber::CucumberExpressions::CucumberExpressionError)**

C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/argument.rb:15:in `build'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/regular_expression.rb:43:in `match'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/glue/step_definition.rb:101:in `arguments_from'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:66:in `block in step_matches'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:65:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:65:in `reduce'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/glue/registry_and_more.rb:65:in `step_matches'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:19:in `call'
C:/Ruby23/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/step_match_search.rb:62:in `call'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:66:in `matches'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:47:in `result'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:37:in `find_match'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:33:in `attempt_to_activate'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `map'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:29:in `new_test_steps'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:23:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/filter.rb:62:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/compiler.rb:24:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:32:in `parse'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-core-3.0.0/lib/cucumber/core.rb:21:in `compile'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:74:in `run!'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
C:/Ruby23/lib/ruby/gems/2.3.0/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
C:/Ruby23/bin/cucumber:22:in `load'
C:/Ruby23/bin/cucumber:22:in `<main>'

Ruby - ruby 2.3.3p222

*** GEM LISTS ***
cucumber (3.0.1)
cucumber-core (3.0.0)
cucumber-expressions (4.0.3, 4.0.0)
cucumber-tag_expressions (1.0.1)
cucumber-wire (0.0.1)
gherkin (4.1.3)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
rubyzip (1.2.1)
selenium-cucumber (3.1.5)
selenium-webdriver (3.6.0, 3.4.0)

**Comment by sameer49** [comment]
able to reproduce.

**Comment by sameer49** [comment]
there has been updates in cucumber regular expressions
https://docs.cucumber.io/cucumber-expressions/

due to this few pre defined steps are failing

**Comment by sameer49** [comment]
update cucumber gems
use cucumber-expressions 4.0.4 and above
