### ISSUE TITLE
Few canned methods are not recognized in Capyabra

### ISSUE THREAD

**Issue by Aravin** [selenium-cucumber/selenium-cucumber-ruby#4]
Even while using the canned steps the cucumber is not recognizing.

i.e `You can implement step definitions for undefined steps with these snippets:` alert is displayed.

for few canned steps,

**example**:
Then I should see alert text as "(._?)"
Then I select "(._?)" option by text from dropdown having id "(._?)"
Then I select "(._?)" option by text from dropdown having name "(._?)"
Then I select "(._?)" option by text from dropdown having class "(._?)"
Then I select "(._?)" option by text from dropdown having xpath "(._?)"
Then I select "(._?)" option by text from dropdown having css "(.*?)"

---

System: Windows 7 x64
Ruby Version: 2.1.7p400 (2015-08-18 revision 51632) [x64-mingw32]
Capybara: capybara (2.5.0, 2.4.4)
Cucumber: cucumber (2.1.0, 1.3.20)

**Comment by sameer49** [comment]
Do you have selenium-cucumber gem installed ?

**Comment by Carlbc18** [comment]
I believe the issue here is that Capybara doesn't implement a global instance of the Selenium::Driver.   If you instantiate the Capybara webdriver following the readme $driver is not defined.  If i'm mistaken, please correct me.

**Comment by Aravin** [comment]
Is this issue? or my mistake?

**Comment by sameer49** [comment]
then you need to initialise $driver with capybara driver instance.

**Comment by Carlbc18** [comment]
@sameer49 is right, and you can achieve that by assigning `$driver = Capybara.current_session.driver.browser` then everything should work.

**Comment by XinWangRita** [comment]
@Carlbc18 your answer help me a lot, thank you so much!
$driver = Capybara.current_session.driver.browser then everything works.

**Comment by Carlbc18** [comment]
Glad it worked. I commented in your other post as well. Thanks.

**Comment by jaythang22** [comment]
When I added this $driver = Capybara.current_session.driver.browser
shows me an error "rack-test requires a rack application, but none was given"
But when I added required rack-test and rack it shows me this error cannot load such file -- rack-test (LoadError)

Need assistance --- running in loop

**Comment by Carlbc18** [comment]
When you instantiated your capybara driver you must not have provided a browser type. Place you're capybara init code for more help

**Comment by jaythang22** [comment]
begin
    
    $driver = Capybara.current_session.driver.browser
    $driver = Selenium::WebDriver.for(:"#{$browser_type}")
    $driver.manage().window().maximize()
  rescue Exception => e
    puts e.message
    Process.exit(0)
  end

end

**Comment by Carlbc18** [comment]
@jaythang22 I was expecting to see something more like... 

`Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end`

which then would then initialize the 'Capybara' driver, which then you can reach into Capybara and assign the selenium instance to the global $driver variable. 

In the code you've pasted above, i don't think you're using Capybara, and you can probably remove
`$driver = Capybara.current_session.driver.browser`
and be just fine.

**Comment by jaythang22** [comment]
@carlbc18 I would try your suggestion. Will provide info

**Comment by jaythang22** [comment]
Here is how i pasted it: Sorry quite confused now @Carlbc18 

 begin
Capybara.register_driver :selenium do |app| 
Capybara::Selenium::Driver.new(app, :browser => :chrome) 
end
    $driver = Selenium::WebDriver.for(:"#{$browser_type}")
    $driver.manage().window().maximize()
  rescue Exception => e
    puts e.message
    Process.exit(0)
  end


===
It still opens a browser and not accessing my Capybara ..... Where did I do wrong?

**Comment by jaythang22** [comment]
finally.......

  begin
    $driver = Appium::Driver.new(desired_caps).start_driver
  rescue Exception => e
    puts e.message
    Process.exit(0)  
  end
else # else create driver instance for desktop browser
  begin
Capybara.register_driver :selenium do |app| 
Capybara::Selenium::Driver.new(app, :browser => :chrome) 
end
    #$driver = Selenium::WebDriver.for(:"#{$browser_type}")
    #$driver.manage().window().maximize()
  rescue Exception => e
    puts e.message
    Process.exit(0)
  end

end

had it working now :) thanks @Carlbc18

**Comment by jaythang22** [comment]
@Carlbc18 one more thing when I add my steps coming from Selenium builder I tried using Capybara

uninitialized constant Capybara::WebDriver (NameError)

**Comment by jaythang22** [comment]
uninitialized constant Capybara::Selenium::WebDriver


When I try it on my driver
custom_steps.rb
wd = Capybara::Selenium::WebDriver.for :firefox

env.rb
else # else create driver instance for desktop browser
  begin
    Capybara.register_driver :selenium do |app| 
      Capybara::Selenium::Driver.new(app, :browser => :firefox) 
    end
    $driver = Capybara::Selenium::WebDriver.for(:"#{$browser_type}")
    #$driver = Selenium::WebDriver.for(:"#{$browser_type}")
    #$driver.manage().window().maximize()
  rescue Exception => e
