### ISSUE TITLE
Error when try to run android app

### ISSUE THREAD

**Issue by kfranklint** [selenium-cucumber/selenium-cucumber-ruby#5]
When i try to start Android App sample i receive this msg, firefox starts and calculator.feature does not work. would yo help me?

Messsage received:
WARNING: cannot load such file -- 2.1/gherkin_lexer_en
Couldn't load 2.1/gherkin_lexer_en
The $LOAD_PATH was:

**Comment by sameer49** [comment]
Ruby version must be 32bit.

**Comment by kfranklint** [comment]
Thank you very much
Em 05/11/2015 06:28, "Sameer Sawant" notifications@github.com escreveu:
